import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';

//Sandbox Server
// const API_URL = "https://api.sandbox.taweethapisek.ac.th/apps/auth/";

//Real Server
const API_URL = 'https://api.taweethapisek.ac.th/apps/';

//Test Server
// const API_URL = "http://localhost:8081/apps/";

//httpOptions
const httpOptions = {
  headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
};

@Injectable({
  providedIn: 'root',
})
export class TpAppsService {
  constructor(private http: HttpClient) {}

  getallstudentsortbyclassroom(
    student_level: any,
    student_classroom: any
  ): Observable<any> {
    return this.http.post(
      API_URL + 'user/student/get/sortbyclassandroom',
      {
        student_level,
        student_classroom,
      },
      httpOptions
    );
  }

  getStudentData(user_id: string): Observable<any> {
    return this.http.get(API_URL + 'user/student/get/' + user_id, httpOptions);
  }

  getStudentDataFull(user_id: string): Observable<any> {
    return this.http.get(
      API_URL + 'user/student/get/by_std_id/' + user_id,
      httpOptions
    );
  }

  updateStudentData(
    student_id: string,
    student_identity_id_type: number,
    student_identity_id: string,
    student_nameprefix_th: string,
    student_firstname_th: string,
    student_surname_th: string,
    student_gender: string,
    student_birthday: string,
    student_nationality: string,
    student_race: string,
    student_religion: string,
    student_old_level: string,
    student_old_school: string,
    student_old_school_subdistrict: string,
    student_old_school_district: string,
    student_old_school_province: string,
    student_house_no: string,
    student_village_no: string,
    student_addr_alley: string,
    student_addr_lane: string,
    student_addr_street: string,
    student_addr_subdistrict: string,
    student_addr_district: string,
    student_addr_province: string,
    student_addr_postal_code: string,
    student_addr_country: string,
    student_tel: string,
    student_mobile: string,
    student_email: string,
    father_NameTH_Prefix: string,
    father_NameTH_FirstName: string,
    father_NameTH_SurName: string,
    father_occupation: string,
    father_tel: string,
    father_mobile: string,
    mother_NameTH_Prefix: string,
    mother_NameTH_FirstName: string,
    mother_NameTH_SurName: string,
    mother_occupation: string,
    mother_tel: string,
    mother_mobile: string,
    parent_NameTH_Prefix: string,
    parent_NameTH_FirstName: string,
    parent_NameTH_SurName: string,
    parent_relationship: string,
    parent_occupation: string,
    parent_tel: string,
    parent_mobile: string,
    m3_sci_1: number,
    m3_sci_2: number,
    m3_math_1: number,
    m3_math_2: number,
    m3_eng_1: number,
    m3_eng_2: number,
    edu: number,
    belong: number
  ): Observable<any> {
    return this.http.post(
      API_URL + 'user/student/edit/by_std_id',
      {
        student_id,
        student_identity_id_type,
        student_identity_id,
        student_nameprefix_th,
        student_firstname_th,
        student_surname_th,
        student_gender,
        student_birthday,
        student_nationality,
        student_race,
        student_religion,
        student_old_level,
        student_old_school,
        student_old_school_subdistrict,
        student_old_school_district,
        student_old_school_province,
        student_house_no,
        student_village_no,
        student_addr_alley,
        student_addr_lane,
        student_addr_street,
        student_addr_subdistrict,
        student_addr_district,
        student_addr_province,
        student_addr_postal_code,
        student_addr_country,
        student_tel,
        student_mobile,
        student_email,
        father_NameTH_Prefix,
        father_NameTH_FirstName,
        father_NameTH_SurName,
        father_occupation,
        father_tel,
        father_mobile,
        mother_NameTH_Prefix,
        mother_NameTH_FirstName,
        mother_NameTH_SurName,
        mother_occupation,
        mother_tel,
        mother_mobile,
        parent_NameTH_Prefix,
        parent_NameTH_FirstName,
        parent_NameTH_SurName,
        parent_relationship,
        parent_occupation,
        parent_tel,
        parent_mobile,
        m3_sci_1,
        m3_sci_2,
        m3_math_1,
        m3_math_2,
        m3_eng_1,
        m3_eng_2,
        edu,
        belong,
      },
      httpOptions
    );
  }

  UpdateStudentDataFull(
    student_id: number,
    student_identity_id_type: string,
    student_identity_id: string,
    student_nameprefix_th: string,
    student_firstname_th: string,
    student_surname_th: string,
    student_nameprefix_en: string,
    student_fristname_en: string,
    student_surname_en: string,
    student_gender: string,
    student_blood_group: string,
    student_birthday: string,
    student_birthplace: string,
    student_birthplace_subdistrict: string,
    student_birthplace_district: string,
    student_birthplace_province: string,
    student_birthplace_country: string,
    student_nationality: string,
    student_race: string,
    student_religion: string,
    student_weight: string,
    student_height: string,
    student_old_level: string,
    student_old_school: string,
    student_old_school_street: string,
    student_old_school_subdistrict: string,
    student_old_school_district: string,
    student_old_school_province: string,
    student_old_school_country: string,
    student_house_id: string,
    student_house_no: string,
    student_village_no: string,
    student_addr_alley: string,
    student_addr_lane: string,
    student_addr_street: string,
    student_addr_subdistrict: string,
    student_addr_district: string,
    student_addr_province: string,
    student_addr_postal_code: string,
    student_addr_country: string,
    student_tel: string,
    student_mobile: string,
    student_email: string,
    student_name_changed_date: string,
    student_old_fristname_th: string,
    student_old_surname_th: string,
    contactable_house_id: string,
    contactable_house_no: string,
    contactable_village_no: string,
    contactable_addr_alley: string,
    contactable_addr_lane: string,
    contactable_addr_street: string,
    contactable_addr_subdistrict: string,
    contactable_addr_district: string,
    contactable_addr_province: string,
    contactable_addr_postal_code: string,
    contactable_addr_country: string,
    contactable_tel: string,
    contactable_mobile: string,
    contactable_email: string,
    father_mother_relationship: string,
    parent_dependent_child_amount: string,
    student_disability: string,
    student_disability_description: string,
    student_disease: string,
    student_disease_treatment_hospital: string,
    student_older_brother_amount: string,
    student_younger_brother_amount: string,
    student_older_sister_amount: string,
    student_younger_sister_amount: string,
    student_child_number: string,
    student_accommodation: string,
    student_home_to_school_distance: string,
    student_transportation: string,
    student_insufficient: string,
    father_IdentityID_type: string,
    father_IdentityID: string,
    father_NameTH_Prefix: string,
    father_NameTH_FirstName: string,
    father_NameTH_SurName: string,
    father_birthday: string,
    father_blood_group: string,
    father_status: string,
    father_race: string,
    father_nationality: string,
    father_religion: string,
    father_occupation: string,
    father_salary: string,
    father_workplace: string,
    father_workplace_subdistrict: string,
    father_workplace_district: string,
    father_workplace_province: string,
    father_workplace_tel: string,
    father_house_id: string,
    father_house_no: string,
    father_village_no: string,
    father_addr_alley: string,
    father_addr_lane: string,
    father_addr_street: string,
    father_addr_subdistrict: string,
    father_addr_district: string,
    father_addr_province: string,
    father_addr_postal_code: string,
    father_addr_country: string,
    father_tel: string,
    father_mobile: string,
    father_email: string,
    mother_IdentityID_type: string,
    mother_IdentityID: string,
    mother_NameTH_Prefix: string,
    mother_NameTH_FirstName: string,
    mother_NameTH_SurName: string,
    mother_birthday: string,
    mother_blood_group: string,
    mother_status: string,
    mother_race: string,
    mother_nationality: string,
    mother_religion: string,
    mother_occupation: string,
    mother_salary: string,
    mother_workplace: string,
    mother_workplace_subdistrict: string,
    mother_workplace_district: string,
    mother_workplace_province: string,
    mother_workplace_tel: string,
    mother_house_id: string,
    mother_house_no: string,
    mother_village_no: string,
    mother_addr_alley: string,
    mother_addr_lane: string,
    mother_addr_street: string,
    mother_addr_subdistrict: string,
    mother_addr_district: string,
    mother_addr_province: string,
    mother_addr_postal_code: string,
    mother_addr_country: string,
    mother_tel: string,
    mother_mobile: string,
    mother_email: string,
    parent_IdentityID_type: string,
    parent_IdentityID: string,
    parent_NameTH_Prefix: string,
    parent_NameTH_FirstName: string,
    parent_NameTH_SurName: string,
    parent_birthday: string,
    parent_blood_group: string,
    parent_race: string,
    parent_nationality: string,
    parent_religion: string,
    parent_relationship: string,
    parent_occupation: string,
    parent_salary: string,
    parent_workplace: string,
    parent_workplace_alley: string,
    parent_workplace_lane: string,
    parent_workplace_street: string,
    parent_workplace_subdistrict: string,
    parent_workplace_district: string,
    parent_workplace_province: string,
    parent_workplace_tel: string,
    parent_house_id: string,
    parent_house_no: string,
    parent_vilage_no: string,
    parent_addr_alley: string,
    parent_addr_lane: string,
    parent_addr_street: string,
    parent_addr_subdistrict: string,
    parent_addr_district: string,
    parent_addr_province: string,
    parent_addr_postal_code: string,
    parent_addr_country: string,
    parent_tel: string,
    parent_mobile: string,
    parent_email: string,
  ): Observable<any> {
    return this.http.post(
      API_URL + 'user/student/edit/by_std_id',
      {
        student_id,
        student_identity_id_type,
        student_identity_id,
        student_nameprefix_th,
        student_firstname_th,
        student_surname_th,
        student_nameprefix_en,
        student_fristname_en,
        student_surname_en,
        student_gender,
        student_blood_group,
        student_birthday,
        student_birthplace,
        student_birthplace_subdistrict,
        student_birthplace_district,
        student_birthplace_province,
        student_birthplace_country,
        student_nationality,
        student_race,
        student_religion,
        student_weight,
        student_height,
        student_old_level,
        student_old_school,
        student_old_school_street,
        student_old_school_subdistrict,
        student_old_school_district,
        student_old_school_province,
        student_old_school_country,
        student_house_id,
        student_house_no,
        student_village_no,
        student_addr_alley,
        student_addr_lane,
        student_addr_street,
        student_addr_subdistrict,
        student_addr_district,
        student_addr_province,
        student_addr_postal_code,
        student_addr_country,
        student_tel,
        student_mobile,
        student_email,
        student_name_changed_date,
        student_old_fristname_th,
        student_old_surname_th,
        contactable_house_id,
        contactable_house_no,
        contactable_village_no,
        contactable_addr_alley,
        contactable_addr_lane,
        contactable_addr_street,
        contactable_addr_subdistrict,
        contactable_addr_district,
        contactable_addr_province,
        contactable_addr_postal_code,
        contactable_addr_country,
        contactable_tel,
        contactable_mobile,
        contactable_email,
        father_mother_relationship,
        parent_dependent_child_amount,
        student_disability,
        student_disability_description,
        student_disease,
        student_disease_treatment_hospital,
        student_older_brother_amount,
        student_younger_brother_amount,
        student_older_sister_amount,
        student_younger_sister_amount,
        student_child_number,
        student_accommodation,
        student_home_to_school_distance,
        student_transportation,
        student_insufficient,
        father_IdentityID_type,
        father_IdentityID,
        father_NameTH_Prefix,
        father_NameTH_FirstName,
        father_NameTH_SurName,
        father_birthday,
        father_blood_group,
        father_status,
        father_race,
        father_nationality,
        father_religion,
        father_occupation,
        father_salary,
        father_workplace,
        father_workplace_subdistrict,
        father_workplace_district,
        father_workplace_province,
        father_workplace_tel,
        father_house_id,
        father_house_no,
        father_village_no,
        father_addr_alley,
        father_addr_lane,
        father_addr_street,
        father_addr_subdistrict,
        father_addr_district,
        father_addr_province,
        father_addr_postal_code,
        father_addr_country,
        father_tel,
        father_mobile,
        father_email,
        mother_IdentityID_type,
        mother_IdentityID,
        mother_NameTH_Prefix,
        mother_NameTH_FirstName,
        mother_NameTH_SurName,
        mother_birthday,
        mother_blood_group,
        mother_status,
        mother_race,
        mother_nationality,
        mother_religion,
        mother_occupation,
        mother_salary,
        mother_workplace,
        mother_workplace_subdistrict,
        mother_workplace_district,
        mother_workplace_province,
        mother_workplace_tel,
        mother_house_id,
        mother_house_no,
        mother_village_no,
        mother_addr_alley,
        mother_addr_lane,
        mother_addr_street,
        mother_addr_subdistrict,
        mother_addr_district,
        mother_addr_province,
        mother_addr_postal_code,
        mother_addr_country,
        mother_tel,
        mother_mobile,
        mother_email,
        parent_IdentityID_type,
        parent_IdentityID,
        parent_NameTH_Prefix,
        parent_NameTH_FirstName,
        parent_NameTH_SurName,
        parent_birthday,
        parent_blood_group,
        parent_race,
        parent_nationality,
        parent_religion,
        parent_relationship,
        parent_occupation,
        parent_salary,
        parent_workplace,
        parent_workplace_alley,
        parent_workplace_lane,
        parent_workplace_street,
        parent_workplace_subdistrict,
        parent_workplace_district,
        parent_workplace_province,
        parent_workplace_tel,
        parent_house_id,
        parent_house_no,
        parent_vilage_no,
        parent_addr_alley,
        parent_addr_lane,
        parent_addr_street,
        parent_addr_subdistrict,
        parent_addr_district,
        parent_addr_province,
        parent_addr_postal_code,
        parent_addr_country,
        parent_tel,
        parent_mobile,
        parent_email,
      },
      httpOptions
    );
  }
}
